export type Product = {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  tagline: string;
  heroHeadline: string;
  heroSubtext: string;
  description: string;
  image: string;
  bgColor: string;
  bgColorDark: string;
  accentColor: string;
  textColor: "light" | "dark";
  category: "sparkling" | "still" | "mixer" | "flavoured";
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
  sizes: string[];
  features: string[];
  usageOccasions: string[];
};
